name: locbadge
run-name: Create lines of code badge
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Lines of Code Badge
        # You may pin to the exact commit or the version.
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          # The directory to scan.
          directory: ./
          # The output path to save the badge svg - including extension!
          badge: ./badge.svg
          # The file patterns to ignore, even if they matched "patterns", separated by pipes ("|").
          ignore: node_modules
          # The label to use for the badge.
          badge_label: Lines of Code
          # The color to use for the badge.
          badge_color: blue
          # The body style to use for the badge. ('flat' or 'classic')
          badge_style: classic
          # The scale to resize this badge
          badge_scale: 1
          # The color to use for this badge label.
          badge_labelcolor: 555
          # Enable debug logging
          debug: false
